# -*- coding: utf-8 -*-
"""Internship Task 3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Y244wtrVNUgepGV0Scu1LteV7cY9P5Tg

Write a Python script using the openpyxl library to read data from an Excel spreadsheet, manipulate
the data, and write the results back to a new spreadsheet.
The Excel spreadsheet should have the following format:

1. The data should be in a table with a header row and at least one row of data.
2. The first column should contain the name of a fruit, and the second column should
contain the quantity of that fruit.
The script should perform the following tasks:

1. Read the data from the Excel spreadsheet.
2. Calculate the total quantity of each fruit.
3. Write the results to a new Excel spreadsheet with the following format:
4. The first column should contain the name of each fruit.
5. The second column should contain the total quantity of that fruit.

For example, if the original spreadsheet contained the following data:


---


Fruit Quantity :
Apple 10
Banana 5
Apple 15
Orange 20
Banana 10

---


[Text Wrapping Break]
The script should create a new spreadsheet with the following data:


---


Fruit Total Quantity :
Apple 25
Banana 15
Orange 20


---


Note: You can create a new Excel spreadsheet using Openpyxl by creating a new Workbook object and adding sheets to it. 
You can write data to a sheet by accessing its cells using row and column indices and setting their values using the "value" attribute.
 You can save the workbook to a file using
the "save" method.

# Importing the openpyxl library
python
"""

import openpyxl

#uploading data into online notebook
from google.colab import files        
uploaded = files.upload()

"""# Opening the original spreadsheet"""

wb = openpyxl.load_workbook('original.xlsx')
sheet = wb.active

"""# Creating a dictionary to store the total quantity of each fruit"""

fruit_totals = {}

"""# Iterating over each row in the spreadsheet and adding the quantity to the total for that fruit"""

for row in sheet.iter_rows(min_row=2, values_only=True):
    fruit = row[0]
    quantity = row[1]
    if fruit in fruit_totals:
        fruit_totals[fruit] += quantity
    else:
        fruit_totals[fruit] = quantity

"""# Creating a new workbook and sheet to store the results"""

new_wb = openpyxl.Workbook()
new_sheet = new_wb.active
new_sheet.title = 'Fruit Totals'

"""# Writing the header row"""

new_sheet.cell(row=1, column=1, value='Fruit')
new_sheet.cell(row=1, column=2, value='Total Quantity')

"""# Writing the fruit and total quantity to each row"""

row_num = 2
for fruit, total in fruit_totals.items():
    new_sheet.cell(row=row_num, column=1, value=fruit)
    new_sheet.cell(row=row_num, column=2, value=total)
    row_num += 1

"""# Saving the new spreadsheet"""

new_wb.save('fruit_totals.xlsx')

print(new_wb)

"""AKULA ZAHEER SHA

---


a.zaheersha@gmail.com

---


9494333702
"""