# -*- coding: utf-8 -*-
"""ML & DS with Python Task 2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1uIJgFtyu8xcAJ_k73PymwAZVPlOvYV-x

# 1. Prepare the Titanic dataset file (download it from Google)
# 2. Find out the names of passengers younger than 35 years.
# 3. Print the rows from index 10 to 25 and columns 3 to 5
# 4. Find out the statistics aggregate of Age & Fare using the DataFrame.agg() method
# 5. Find out the mean ticket fare price for each of the sex and cabin class combinations
"""

import pandas as pd

#uploading data into online notebook
from google.colab import files        
uploaded = files.upload()

#Load the Titanic dataset
df = pd.read_excel("titanic3.xls")

#Print the first 5 rows of the DataFrame
print(df.head())

#Find out the names of passengers younger than 35 years
young_passengers = df[df['age'] < 35]['name'].tolist()
print(young_passengers)

#Print the rows from index 10 to 25 and columns 3 to 5
subset_df = df.iloc[10:26, 3:6]
print(subset_df)

#Find out the statistics aggregate of Age & Fare using the DataFrame.agg() method
agg_df = df[['age', 'fare']].agg(['min', 'max', 'mean', 'median', 'std'])
print(agg_df)

#Find out the mean ticket fare price for each of the sex and cabin class combinations
fare_means = df.groupby(['sex', 'pclass'])['fare'].mean()
print(fare_means)

"""**Akula Zaheer Sha**

---


**a.zaheersha@gmail.com**

---

**9494333702**
"""